import CartIcon from '@/shared/ui/CartIcon/CartIcon'
import Logo from '@/shared/ui/Logo/Logo'
import ProfileIcon from '@/shared/ui/ProfileIcon/ProfileIcon'
import { Header } from '@/widgets/header/Header'
import AppNavigation from '@/widgets/navigation/AppNavigation'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body className={inter.className}>
        <Header
          userInfo={
            <>
              <CartIcon />
              <div className='flex items-center gap-1'>
                <ProfileIcon />
                <span>Профиль</span>
              </div>
            </>
          }
          logo={<Logo />}
          navigation={<AppNavigation />}
        />
        {children}
      </body>
    </html>
  )
}
